-- MySQL Script generated by MySQL Workbench
-- Wed Jul 29 12:50:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `recovery_code_hash` VARCHAR(255) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `module` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_roles` (
  `user_role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_role_id`, `user_id`, `role_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_permission` (
  `role_permission_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`role_permission_id`, `permission_id`, `role_id`),
  INDEX `fk_permissions_has_roles_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_permissions_has_roles_permissions1_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissions_has_roles_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissions_has_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apartments` (
  `apartment_id` INT NOT NULL AUTO_INCREMENT,
  `logo_url` VARCHAR(255) NULL,
  `name_th` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NULL,
  `address_th` VARCHAR(255) NOT NULL,
  `address_en` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `phone` VARCHAR(50) NULL,
  `late_fee_per_day_cents` INTEGER NOT NULL,
  `is_auto_late_fee_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `due_date_day` INT NOT NULL,
  `is_vat_enabled` TINYINT NULL,
  -- เลิกใช้ตั้งแต่ migration 011 — รูปย้ายไปเก็บเป็น BLOB ในตาราง images แล้ว
  -- ไม่เคยมีโค้ดไหนเขียนค่าลงคอลัมน์นี้ ปล่อยว่างไว้ตลอด (ลบทิ้งต้องสร้างตารางใหม่ทั้งใบ)
  `qr_code_image` VARCHAR(255) NULL,
  -- QR รับเงินตัวจริง (migration 011) — NULL = ยังไม่ได้อัปโหลด ใบแจ้งหนี้ก็ยังออกได้
  `qr_code_image_id` INT NULL,
  `payment_instructions` TEXT NULL,
  `show_tenant_info_in_invoice` TINYINT(1) NOT NULL DEFAULT 1,
  `show_unit_qty_in_invoice` TINYINT(1) NOT NULL DEFAULT 1,
  `default_rent_item_text` VARCHAR(255) NULL DEFAULT 'ค่าเช่าห้อง/Rent',
  -- เวลาที่เดินตัวช่วยตั้งค่าครบ 8 ขั้น (migration 008) — NULL = ยังตั้งค่าไม่เสร็จ
  -- หอที่ยัง NULL อยู่จะเข้าหน้าทำงานที่มีเมนูข้างไม่ได้ ต้องกลับไปตั้งค่าให้จบก่อน
  `setup_completed_at` TIMESTAMP NULL,
  -- ค่าตั้งต้นกฎคืนเงินประกัน (migration 004) — NULL = ใช้ระยะสัญญาของแต่ละใบเป็นเกณฑ์
  `default_deposit_min_stay_months` INT NULL,
  `default_deposit_notice_days` INT NOT NULL DEFAULT 15,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`apartment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apartment_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apartment_services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price_cents` INTEGER NOT NULL,
  `is_vat_enabled` TINYINT NULL,
  `is_meter_based` TINYINT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_apartmant_services_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartmant_services_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apartment_bank_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apartment_bank_accounts` (
  `bank_account_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_id` INT NOT NULL,
  `bank_name` VARCHAR(100) NULL,
  `account_name` VARCHAR(255) NULL,
  `account_number` VARCHAR(50) NULL,
  `is_default` TINYINT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`bank_account_id`),
  INDEX `fk_apartment_bank_accounts_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartment_bank_accounts_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`floors` (
  `floor_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_id` INT NOT NULL,
  `floor_name` VARCHAR(50) NOT NULL,
  `room_count` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`floor_id`),
  INDEX `fk_floors_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_floors_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_types` (
  `room_type_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`room_type_id`),
  INDEX `fk_room_types_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_types_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `floor_id` INT NOT NULL,
  `room_type_id` INT NOT NULL,
  `room_number` VARCHAR(50) NOT NULL,
  `is_active` TINYINT NOT NULL,
  `monthly_rent_cents` INTEGER NOT NULL,
  `daily_rent_cents` INTEGER NULL,
  `status` ENUM('vacant', 'occupied', 'maintenance') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_rooms_floors1_idx` (`floor_id` ASC) VISIBLE,
  INDEX `fk_rooms_room_types1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_rooms_floors1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `mydb`.`floors` (`floor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooms_room_types1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `mydb`.`room_types` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_utility_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_utility_settings` (
  `utility_setting_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `is_water_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `water_billing_type` ENUM('actual', 'minimum', 'flat') NOT NULL,
  `water_unit_price_cents` INTEGER NOT NULL,
  `water_min_charge_cents` INTEGER NOT NULL,
  `water_flat_rate_cents` INTEGER NOT NULL,
  `show_water_reading_in_invoice` TINYINT(1) NOT NULL DEFAULT 1,
  `is_electric_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `electric_billing_type` ENUM('actual', 'minimum', 'flat') NOT NULL,
  `electric_unit_price_cents` INTEGER NOT NULL,
  `electric_min_charge_cents` INTEGER NOT NULL,
  `electric_flat_rate_cents` INTEGER NOT NULL,
  `show_electric_reading_in_invoice` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`utility_setting_id`),
  UNIQUE INDEX `room_id_UNIQUE` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_utility_settings_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_services` (
  `room_service_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_service_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`room_service_id`, `apartment_service_id`, `room_id`),
  INDEX `fk_apartmant_services_has_rooms_rooms1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_apartmant_services_has_rooms_apartmant_services1_idx` (`apartment_service_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartmant_services_has_rooms_apartmant_services1`
    FOREIGN KEY (`apartment_service_id`)
    REFERENCES `mydb`.`apartment_services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartmant_services_has_rooms_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_apartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_apartments` (
  `users_apartments_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`users_apartments_id`, `user_id`, `apartment_id`),
  INDEX `fk_users_has_apartments_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  INDEX `fk_users_has_apartments_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_apartments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_apartments_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tenants` (
  `tenant_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `id_card_no` VARCHAR(50) NOT NULL,
  `address` TEXT NULL,
  `emergency_contact_name` VARCHAR(150) NULL,
  `emergency_relation` VARCHAR(50) NULL,
  `emergency_phone` VARCHAR(50) NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`tenant_id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `id_card_no_UNIQUE` (`id_card_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contracts` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `rent_type` ENUM('monthly', 'daily') NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `rent_amount_cents` INTEGER NOT NULL,
  `deposit_amount_cents` INTEGER NOT NULL,
  `deposit_payment_method` VARCHAR(50) NOT NULL,
  `booking_fee_cents` INTEGER NOT NULL,
  `booking_receipt_no` VARCHAR(100) NULL,
  `advance_payment_amount_cents` INTEGER NOT NULL,
  `water_meter_start` DECIMAL(10,2) NOT NULL,
  `electric_meter_start` DECIMAL(10,2) NOT NULL,
  `note` TEXT NULL,
  `status` ENUM('active', 'inactive') NOT NULL,
  -- กฎคืนเงินประกัน (migration 004) — snapshot ไว้ที่สัญญาตอนเซ็น ไม่อ่านจาก apartments
  -- ตอนคำนวณ เพื่อให้การเปลี่ยนกฎของหอไม่ย้อนหลังไปกระทบสัญญาที่เซ็นไปแล้ว
  `term_months` INT NULL,
  `deposit_refund_policy` ENUM('on_full_term', 'always', 'never') NOT NULL DEFAULT 'on_full_term',
  `deposit_min_stay_months` INT NULL,
  `deposit_notice_days` INT NOT NULL DEFAULT 15,
  -- สายการต่อสัญญา: ใช้ไล่ย้อนเพื่อนับเดือนที่อยู่ต่อเนื่องข้ามสัญญาหลายใบ
  `previous_contract_id` INT NULL,
  `is_deposit_carried_over` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`contract_id`, `room_id`, `tenant_id`),
  INDEX `fk_rooms_has_tenants_tenants1_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_rooms_has_tenants_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_rooms_has_tenants_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooms_has_tenants_tenants1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenants` (`tenant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract_services` (
  `contract_service_id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `apartment_service_id` INT NOT NULL,
  `price_cents` INTEGER NOT NULL,
  PRIMARY KEY (`contract_service_id`, `contract_id`, `apartment_service_id`),
  INDEX `fk_contracts_has_apartment_services_apartment_services1_idx` (`apartment_service_id` ASC) VISIBLE,
  INDEX `fk_contracts_has_apartment_services_contracts1_idx` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_has_apartment_services_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`contracts` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contracts_has_apartment_services_apartment_services1`
    FOREIGN KEY (`apartment_service_id`)
    REFERENCES `mydb`.`apartment_services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_bookings` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  -- เพิ่มใน 013: เลขที่ใบจอง B2026080001 = 'B' + YYYYMM + ลำดับ 4 หลัก
  -- เดินเลขด้วย document_counters ชุดเดียวกับใบแจ้งหนี้/ใบเสร็จ (doc_type = 'booking')
  -- NULL ได้ เพราะใบจองที่บันทึกไว้ก่อนหน้านี้ไม่มีเลข
  `booking_number` VARCHAR(50) NULL,
  `rent_type` ENUM('monthly', 'daily') NOT NULL,
  `check_in_date` DATE NOT NULL,
  `check_out_date` DATE NULL,
  `booking_date` DATE NOT NULL,
  `rent_price_cents` INTEGER NOT NULL,
  `booking_fee_cents` INTEGER NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_phone` VARCHAR(50) NOT NULL,
  `note` TEXT NULL,
  `status` ENUM('pending', 'confirmed', 'converted_to_contract', 'cancelled') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `idx_room_bookings_number` (`booking_number` ASC) VISIBLE,
  INDEX `fk_room_bookings_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_bookings_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract_terminations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract_terminations` (
  `termination_id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `notice_date` DATE NOT NULL,
  `actual_move_out_date` DATE NOT NULL,
  `deposit_snapshot_cents` INTEGER NOT NULL,
  `unpaid_invoices_total_cents` INTEGER NOT NULL,
  `additional_adjustments_total_cents` INTEGER NOT NULL,
  -- ยอดสุทธิ "ติดลบได้" = ริบเงินประกันแล้วผู้เช่ายังค้างบิลอยู่ ต้องเรียกเก็บเพิ่ม
  `net_refund_amount_cents` INTEGER NOT NULL,
  -- ผลการตัดสินตามกฎคืนเงินประกัน (migration 004)
  -- notice_date เป็น NOT NULL อยู่แล้ว คนที่ออกโดยไม่แจ้งจึงใช้ is_notice_given = 0
  -- แล้วใส่ notice_date เป็นวันที่ทราบว่าย้ายออกแทน
  `is_notice_given` TINYINT(1) NOT NULL DEFAULT 1,
  `notice_days_given` INT NULL,
  `months_stayed_total` INT NULL,
  `is_deposit_refundable` TINYINT(1) NOT NULL DEFAULT 1,
  `forfeit_reason` ENUM('early_move_out', 'insufficient_notice', 'both', 'policy_never') NULL,
  `refundable_deposit_cents` INTEGER NOT NULL DEFAULT 0,
  `is_manual_override` TINYINT(1) NOT NULL DEFAULT 0,
  `override_reason` TEXT NULL,
  `status` ENUM('draft', 'completed', 'cancelled') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`termination_id`),
  INDEX `fk_contract_terminations_contracts1_idx` (`contract_id` ASC) VISIBLE,
  UNIQUE INDEX `contract_id_UNIQUE` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_terminations_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`contracts` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract_termination_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract_termination_items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `contract_termination_id` INT NOT NULL,
  `item_type` ENUM('service', 'discount_refund', 'water', 'electricity') NULL,
  `description` VARCHAR(255) NULL,
  `amount_before_vat_cents` INTEGER NULL,
  `vat_percent` DECIMAL(5,2) NULL,
  `vat_amount_cents` INTEGER NULL,
  `total_amount_cents` INTEGER NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_contract_termination_items_contract_terminations1_idx` (`contract_termination_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_termination_items_contract_terminations1`
    FOREIGN KEY (`contract_termination_id`)
    REFERENCES `mydb`.`contract_terminations` (`termination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maintenance_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maintenance_requests` (
  `maintenance_id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `reported_date` DATE NOT NULL,
  `appointment_date` DATE NOT NULL,
  `status` ENUM('pending', 'completed', 'cancelled') NOT NULL,
  `description` TEXT NOT NULL,
  `image_url` VARCHAR(255) NULL,
  `repaired_date` DATE NOT NULL,
  `repair_cost_cents` INTEGER NOT NULL,
  `repair_details` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`maintenance_id`),
  INDEX `fk_maintenance_requests_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_maintenance_requests_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meter_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meter_batches` (
  `batch_id` INT NOT NULL AUTO_INCREMENT,
  `apartment_id` INT NOT NULL,
  `reading_date` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`batch_id`),
  INDEX `fk_meter_batches_apartments1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_meter_batches_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meter_readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meter_readings` (
  `meter_reading_id` INT NOT NULL AUTO_INCREMENT,
  `meter_batch_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  -- 014: ยอมให้เป็น NULL ได้ — NULL = ฝั่งนี้ยังไม่ได้จดในรอบนี้ · 0 = จดแล้วอ่านได้ 0
  -- หน้าจอกรอกทีละฝั่ง ถ้าเขียนอีกฝั่งเป็น 0 ไว้ก่อน ฝั่งนั้นจะหยุดไล่หาเลขครั้งก่อน
  `water_previous_reading` DECIMAL(10,2) NULL,
  `water_current_reading` DECIMAL(10,2) NULL,
  `water_units_used` DECIMAL(10,2) NULL,
  `is_water_over_cycle` TINYINT(1) NULL,
  `electric_previous_reading` DECIMAL(10,2) NULL,
  `electric_current_reading` DECIMAL(10,2) NULL,
  `electric_units_used` DECIMAL(10,2) NULL,
  `is_electric_over_cycle` TINYINT(1) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`meter_reading_id`),
  INDEX `fk_meter_readings_meter_batches1_idx` (`meter_batch_id` ASC) VISIBLE,
  INDEX `fk_meter_readings_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_meter_readings_meter_batches1`
    FOREIGN KEY (`meter_batch_id`)
    REFERENCES `mydb`.`meter_batches` (`batch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meter_readings_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoices` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `invoice_number` VARCHAR(50) NOT NULL,
  `billing_month` VARCHAR(7) NOT NULL,
  `issue_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `status` ENUM('unpaid', 'partial_paid', 'paid', 'cancelled') NOT NULL,
  -- เพิ่มใน 012: บิลรายเดือน (ออกยกล็อตจากใบจดมิเตอร์) vs ใบแจ้งหนี้ทั่วไป (ออกใบเดี่ยว)
  `invoice_type` ENUM('monthly', 'general') NOT NULL DEFAULT 'monthly',
  -- เพิ่มใน 012: บิลรายเดือนมาจากการจดมิเตอร์รอบไหน (ใบแจ้งหนี้ทั่วไปเป็น NULL)
  `meter_batch_id` INT NULL,
  `exempt_amount_cents` INTEGER NOT NULL,
  `taxable_amount_cents` INTEGER NOT NULL,
  `vat_amount_cents` INTEGER NOT NULL,
  `total_amount_cents` INTEGER NOT NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  -- เพิ่มใน 012: บิลที่ถูกยกเลิกต้องรู้ว่ายกเลิกเมื่อไหร่
  `cancelled_at` TIMESTAMP NULL,
  PRIMARY KEY (`invoice_id`),
  -- 012: เลขที่ใบแจ้งหนี้ห้ามซ้ำ และหนึ่งสัญญาออกบิลรายเดือนได้เดือนละใบ (ที่ยังไม่ยกเลิก)
  UNIQUE INDEX `idx_invoices_number` (`invoice_number` ASC) VISIBLE,
  INDEX `fk_invoices_contracts1_idx` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`contracts` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_items` (
  `invoice_item_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `item_type` ENUM('rent', 'water', 'electricity', 'service', 'discount', 'other') NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit_price_cents` INTEGER NOT NULL,
  `vat_rate` DECIMAL(5,2) NOT NULL,
  `vat_amount_cents` INTEGER NOT NULL,
  `total_amount_cents` INTEGER NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`invoice_item_id`),
  INDEX `fk_invoice_items_invoices1_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_items_invoices1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `mydb`.`invoices` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
-- รื้อใหม่ทั้งตารางใน 012 — ของเดิมผูก invoice_item_id ซึ่งผิดสองชั้น:
--   ก) หน้าจอรับเงินของต้นแบบรับเป็นยอดเดียวต่อทั้งใบ ไม่ได้จ่ายรายบรรทัด
--   ข) รายงานใบเสร็จมีประเภท "สัญญา" = ใบเสร็จเงินประกัน/เงินล่วงหน้าตอนทำสัญญา
--      ซึ่งไม่มีใบแจ้งหนี้อยู่เบื้องหลัง
CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NULL,
  `contract_id` INT NULL,
  `receipt_number` VARCHAR(50) NOT NULL,
  `payment_date` DATE NOT NULL,
  -- ติดลบได้ = การคืนเงิน
  `amount_cents` INTEGER NOT NULL,
  `vat_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `payment_method` VARCHAR(255) NOT NULL,
  `remark` TEXT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`payment_id`),
  -- ใบเสร็จหนึ่งใบอ้างอิงต้นทางได้ทางเดียวเท่านั้น ไม่ใช่ทั้งคู่ และไม่ใช่ไม่มีเลย
  CHECK ((`invoice_id` IS NOT NULL) <> (`contract_id` IS NOT NULL)),
  UNIQUE INDEX `idx_payments_receipt_number` (`receipt_number` ASC) VISIBLE,
  INDEX `fk_payments_invoices1_idx` (`invoice_id` ASC) VISIBLE,
  INDEX `fk_payments_contracts1_idx` (`contract_id` ASC) VISIBLE,
  INDEX `fk_payments_users1_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_payments_invoices1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `mydb`.`invoices` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`contracts` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document_counters`   (เพิ่มใน 012)
-- -----------------------------------------------------
-- เดินเลขเอกสาร I2025030018 / R2025030010 = ตัวอักษร + YYYYMM + ลำดับ 4 หลัก
-- ต้องมีตัวนับแยก ไม่ใช่ MAX()+1 เพราะบิลลบได้ ลบใบท้ายแล้วเลขจะถูกใช้ซ้ำ
CREATE TABLE IF NOT EXISTS `mydb`.`document_counters` (
  `apartment_id` INT NOT NULL,
  `doc_type` ENUM('invoice', 'receipt', 'booking') NOT NULL,
  `period` VARCHAR(6) NOT NULL,
  `last_seq` INT NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`apartment_id`, `doc_type`, `period`),
  CONSTRAINT `fk_document_counters_apartments1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`apartments` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `mydb`.`images`  (migration 011)
-- -----------------------------------------------------
-- รูปภาพทุกใบในระบบเก็บเป็น BLOB ที่นี่ ไม่ใช่ไฟล์ในโฟลเดอร์
-- เพราะการสำรองข้อมูลคัดลอกเฉพาะไฟล์ .sqlite — รูปที่อยู่นอกไฟล์จะไม่ติดไปด้วย
--
-- แยกเป็นตารางกลางแทนคอลัมน์ BLOB บนตารางที่ใช้ เพราะ SQLite อ่านทั้งแถวเวลา SELECT
-- ถ้าแปะไว้บน apartments คำสั่ง `SELECT a.*` จะลากรูปขึ้นมาทุกครั้งที่เปิดหน้ารายการหอ
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id`   INT NOT NULL AUTO_INCREMENT,
  `mime_type`  VARCHAR(50) NOT NULL,
  `byte_size`  INT NOT NULL,
  `bytes`      BLOB NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`image_id`)
);

-- -----------------------------------------------------
-- Table `mydb`.`maintenance_request_images`  (migration 011)
-- -----------------------------------------------------
-- หนึ่งงานแจ้งซ่อมมีรูปได้หลายใบ (ก่อนซ่อม / หลังซ่อม) และไม่บังคับว่าต้องมี
CREATE TABLE IF NOT EXISTS `mydb`.`maintenance_request_images` (
  `maintenance_id` INT NOT NULL,
  `image_id`       INT NOT NULL,
  `display_order`  INT NOT NULL DEFAULT 0,
  `created_at`     TIMESTAMP NOT NULL,
  PRIMARY KEY (`maintenance_id`, `image_id`),
  FOREIGN KEY (`maintenance_id`) REFERENCES `mydb`.`maintenance_requests` (`maintenance_id`),
  FOREIGN KEY (`image_id`) REFERENCES `mydb`.`images` (`image_id`)
);
