-- ค่าตั้งต้นของ "นโยบายคืนเงินประกัน" ประจำหอ
--
-- 004 เพิ่มค่าตั้งต้นระดับหอไว้แล้วสองค่า (default_deposit_min_stay_months,
-- default_deposit_notice_days) และ createContract ก็อ่านสองค่านั้นไปสำเนาลงสัญญาใหม่แล้ว
-- แต่ **ตัวนโยบายเองไม่มีคอลัมน์ระดับหอ** — สัญญาทุกใบได้ 'on_full_term' มาจาก DEFAULT
-- ของตาราง contracts ล้วนๆ ซึ่งแปลว่าเปลี่ยนนโยบายของหอไม่ได้เลยแม้จะมีหน้าจอให้ตั้ง
--
-- ค่าที่ใช้ได้: 'on_full_term' (คืนเมื่ออยู่ครบ) | 'always' (คืนเสมอ) | 'never' (ไม่คืน)
-- ตรวจค่าที่ db/apartments.js ก่อนเขียนทุกครั้ง (SQLite ไม่มี ENUM)
--
-- DEFAULT ตรงกับของ contracts เพื่อให้หอที่มีอยู่แล้วไม่เปลี่ยนพฤติกรรมจากการอัปเกรด
-- (เจ้าของหอยืนยัน 2026-08-11 ว่ากติกาจริงคือ "อยู่ครบ 12 เดือน + แจ้ง 15 วัน จึงคืนเต็ม")
ALTER TABLE apartments ADD COLUMN default_deposit_refund_policy TEXT NOT NULL DEFAULT 'on_full_term';
